services:
  - type: web
    name: primelogitech-backend
    env: docker
    repo: https://github.com/Mrcoderv/primelogitech
    branch: Rvbranch
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: 'False'
      - key: PYTHON_VERSION
        value: '3.12'
      - key: PORT
        value: '8000'
    healthCheckPath: /api/
    autoDeployOnPush: true
    maxInstanceCount: 1
    preDeployCommand: |
      cd backend && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput
