# Generated by Django 6.0.5 on 2026-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(default="Remote", max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full Time"),
                            ("part-time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full-time",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.JSONField(default=list)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("image_url", models.URLField(blank=True)),
                ("tech_stack", models.JSONField(default=list)),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("pinned", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-pinned", "order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="Code", max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_badge",
                    models.CharField(
                        default="Prime Logic Tech is now live", max_length=100
                    ),
                ),
                ("hero_heading", models.TextField(default="Design. Develop. Deliver.")),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="We build modern web and mobile solutions for forward-thinking businesses."
                    ),
                ),
                (
                    "hero_cta_primary",
                    models.CharField(default="Start a Project", max_length=80),
                ),
                (
                    "hero_cta_secondary",
                    models.CharField(default="View Our Work", max_length=80),
                ),
                ("trusted_by_logos", models.JSONField(default=list)),
                (
                    "why_title",
                    models.CharField(default="Why Partner With Us", max_length=200),
                ),
                ("why_description", models.TextField(default="")),
                ("why_checklist", models.JSONField(default=list)),
                ("stat_projects", models.CharField(default="150+", max_length=50)),
                ("stat_clients", models.CharField(default="98%", max_length=50)),
                ("stat_team", models.CharField(default="45+", max_length=50)),
                ("stat_experience", models.CharField(default="10+", max_length=50)),
                ("about_mission", models.TextField(default="")),
                ("about_vision", models.TextField(default="")),
                (
                    "cta_heading",
                    models.CharField(
                        default="Ready to Build Something Great?", max_length=200
                    ),
                ),
                ("cta_subtitle", models.TextField(default="")),
                (
                    "cta_button_text",
                    models.CharField(default="Start a Project", max_length=80),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="hello@primelogictech.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+1 (555) 123-4567", max_length=30),
                ),
                (
                    "contact_address",
                    models.CharField(default="Kathmandu, Nepal", max_length=200),
                ),
                ("footer_tagline", models.CharField(default="", max_length=300)),
            ],
            options={
                "verbose_name": "Site Content",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("image_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("quote", models.TextField()),
                ("avatar_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
