# Generated by Django 6.0.5 on 2026-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, default="", max_length=120)),
                ("description", models.TextField()),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="projects/"),
                ),
                ("link", models.URLField(blank=True, default="")),
                (
                    "tech_stack",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
