# Generated by Django 6.0.5 on 2026-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.TextField(blank=True, default=""),
        ),
    ]
