# Generated by Django 6.0.5 on 2026-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="form_link",
            field=models.URLField(
                default="",
                help_text="Link to application form (Google Form, TypeForm, etc.)",
            ),
            preserve_default=False,
        ),
    ]
