# Generated by Django 6.0.5 on 2026-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_job_form_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Pin this project to appear in Featured Work section",
            ),
        ),
    ]
