# Generated by Django 5.1.15 on 2026-05-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_action_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('SMTP_HOST', 'SMTP Host'), ('SMTP_PORT', 'SMTP Port'), ('SMTP_USER', 'SMTP User'), ('SMTP_PASS', 'SMTP Password')], max_length=30, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_messages', to='core.adminuser'),
        ),
    ]
